image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Pit"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

before_script:
  - apt-get update
  - apt-get install -y openjfx bc

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "mvn clean compile $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - transporteditor-editor/target/

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn package $MAVEN_CLI_OPTS"
    - echo "TotalInstructionCoverage:" `cat transporteditor-editor/target/site/jacoco/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
  artifacts:
    paths:
      - transporteditor-editor/target/

integrationtest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - "mvn verify $MAVEN_CLI_OPTS"
    - echo "TotalInstructionCoverage:" `cat transporteditor-editor/target/site/jacoco-it/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
  artifacts:
    paths:
      - transporteditor-editor/target/

deploy-job:
  stage: deploy
  artifacts:
    paths:
      - "target/transporteditor-editor/*.jar"

build-docs:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y asciidoctor texlive-latex-base texlive-fonts-recommended make texlive-latex-extra
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
    - apt-get install git-lfs
    - git lfs install
    - git lfs pull
  script:
    - 'old="`pwd`"'
    - 'cd transporteditor-docs'
    - 'bash build.sh'
    - 'cd "$old"'
  artifacts:
     paths:
        - "transporteditor-docs/target/docs"

